#!/usr/bin/env bash

function stage_usage {
  cat <<HELP

  usage: stage <command>

   command
       deploy               deploy an app in stage
       update-sales         rake data_quality:update
       clean-the-zoo        /opt/gilt/zookeeper/bin/zkCleanup.sh -n 5
       kill-rsync-folders   rm -rf /web/rsync/*
HELP
}

function update_sales {
  cd /web/util-data-quality;
  rake data_quality:update;
  cd -;
}

function clean_the_zoo {
  /opt/gilt/zookeeper/bin/zkCleanup.sh -n 5;
}

function kill_rsync_folders {
  cd /web/rsync;
  rm -rf ./
}

function stage_deploy {
  app=$1
  override=${2-"origin/master"}
  if [ -z "$app" ]; then
cat <<USAGE

    usage: stage deploy <app> <override>

    This command will depoy an app in a stage environment by running
    running the appropriate rake task in setup. The reason it exists is
    that I always forget to delete the less linting cache.

    Examples:

      stage deploy web-product-detail origin/master

      stage deploy web-search gerrit:46482

    Guts:

      This command does the following things;
      1) delete Less-lint cache
      2) cd to /setup
      3) run rake task
USAGE
    return;
  fi

  sudo rm -rf /tmp/Less-lint/;
  cd /setup;
  rake "$app[$override]";
  cd -;
}

function stage {
  action=$1;
  if [ -z "$action" ]; then
    stage_usage;
    return;
 fi

  [ "update-sales" = "$action" ] && update_sales;
  [ "clean-the-zoo" = "$action" ] && shift && clean_the_zoo "$@";
  [ "kill-rsync-folders" = "$action" ] && kill_rsync_folders;
  [ "deploy" = "$action" ] && shift  && stage_deploy "$@";
}
