alias g1="git log --pretty=oneline --abbrev-commit"
alias gb="git branch"
alias gba="git branch -a"
alias gbv="git branch -vvv"
alias gc="git commit -S -v"
alias gca="git commit -v -a -m"
alias gcane="git commit --amend --no-edit"
alias gcf="echo 'use `git fixup` instead'"
alias gci="git commit -S -v -m"
alias gco="git checkout"
alias gcount="git shortlog -sn"
alias gdc="git diff --cached"
alias gdf="git diff HEAD -- . ':(exclude)package-lock.json'"
alias gdt="git difftool HEAD"
alias gg="git grep"
alias gl="git pull --rebase"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gpo="git push origin (current_branch)"
alias gpof="git push --force-with-lease origin (current_branch)"
alias gpu="git push --set-upstream origin (current_branch)"
alias gpr="gh pr create"
alias gprd="gh pr create -d"
alias grh="git reset HEAD"
alias gri="git rebase --interactive"
alias gsh="git ksshow"
alias gst="git status -sb"
alias gsu="git submodule update"
alias gu="git restore --staged"
export OP_PLUGIN_ALIASES_SOURCED=1
alias gh="op plugin run -- gh"

## WIP workflow
alias wip='git commit -am "WIP" --no-verify';
alias unwip='git reset --soft HEAD^';
