#!/opt/homebrew/bin/fish

# Mac App list by app_id
# 904280696   Things
# 411643860   DaisyDisk
# 803453959   Slack

# paths
set -l DOTS $HOME/.dotfiles

# a list of mac applications
set -l app_list 904280696 411643860 803453959;
# a list of Homebrew casks that can't tell if they are Already installed for whatever reason
set -l cask_list "arc" "wezterm"

set -l hb_light F9D094
set -l hb_dark 2e2a24
set -l mac 0362fc

source $DOTS/util_headings

### Start

heading Applications $hb_light $hb_dark
echo

if not command -v brew > /dev/null;
  echo (set_color -o $hb_light)Homebrew not found. Installing Homebrew.(set_color normal);
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if not command -v brew > /dev/null;
    # add path to brew, if not found
    fish_add_path (brew --prefix)/bin/brew;
  end
end

if test -e $HOME/Brewfile;
  echo (set_color $hb_light)Brewfile found. Running (set_color -o $hb_light)brew bundle(set_color $hb_light).(set_color normal)
  cd $HOME;
  brew bundle;
  cd -;
end

if command -v brew > /dev/null;
  echo
  echo Installing (set_color -i $hb_light)Discerning(set_color $hb_light) Homebrew casks(set_color normal);
  cd $HOME;
  for cask in $cask_list
    ## TODO: check for existence of cask Application before installing
    brew install --cask $cask
  end
  cd -;
else
  echo (set_color red)Could not file brew(set_color normal);
end

if command -v mas > /dev/null;
  echo
  echo (set_color -o $mac;)Installing AppStore apps.(set_color normal)
  echo
  for app in $app_list
    mas install $app
  end
end

