# Extra "Nerd Font characters"
# 󱠿       󰯈    
# in case you forget again,
# you can type unicode character by switching
# the keyboard layout to "Unicode Hex Input"
# and then holding option and typing the hex code
#
# Ok, check this out - https://github.com/ryanoasis/powerline-extra-symbols
#

format = """
[  ](fg:#44475A bg:#282A37)$nodejs[$fill$time](bg:#44475A)
[ ](fg:#44475A bg:#282A37)$directory${custom.directory_fill}$git_branch$git_commit $git_status
[](fg:#44475A bg:#282A37)[   ](bg:#44475A)[](fg:#44475A bg:#282A37)$character
"""
right_format = "$battery"
command_timeout = 5000

#
#   Top Line
#

[nodejs]
symbol = ""
format = "[  ](fg:green bg:#44475A)[ $symbol ](bg:green fg:#44475A)[](fg:green bg:bright-blue)[($version) ](bg:bright-blue fg:black)[](fg:bright-blue bg:#44475A)"

[fill]
symbol = " "
style = "bg:#44475A"

[memory_usage]
symbol = " "
disabled = true
threshold = 25
format = "[](green)[ ${ram} :: ${ram_pct} ](bg:green fg:black bold)[](green) "

[time]
disabled = false
format="[](fg:black bg:#44475A)[ $time ](bg:black fg:white)[](fg:black bg:#282A37)"
time_format = "%d %b %Y  %T"

[battery]
format = "[$symbol]($style)"
full_symbol = "󰁹 "
empty_symbol = "󰂎 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁽 "
unknown_symbol = "󰂑 "

[[battery.display]]
threshold = 100
discharging_symbol = "󰁹 "
charging_symbol = "󰂄 "
style = "fg:bright-green bg:#282A37"

[[battery.display]]
threshold = 80
discharging_symbol = "󰁽 "
charging_symbol = "󰂄 "
style = "fg:green bg:#282A37"

[[battery.display]]
threshold = 30
discharging_symbol = "󰁽 "
charging_symbol = "󰂄 "
style = "fg:yellow bg:#282A37"

[[battery.display]]
threshold = 10
discharging_symbol = "󰂎 "
charging_symbol = "󰂄 "
style = "fg:red bg:#282A37"

#
#   Middle Line
#

[custom.directory_fill]
when = '''test (git rev-parse --is-inside-work-tree 2> /dev/null) -n "true"'''
format = '[](fg:cyan bg:#282A37)'

[directory]
truncation_length = 10
format = '[ ](bg:#44475A fg:cyan)[ $path ](bg:cyan fg:black)'

[git_branch]
symbol = " "
always_show_remote = true
format = '[](bg:cyan fg:purple)[ $symbol$branch( 󰤉$remote_name) ](bg:purple fg:black)[](fg:purple bg:#282A37)'
only_attached = true

[git_commit]
format = '[](bg:cyan fg:purple)[  $hash](bg:purple fg:black)[](fg:purple bg:#282A37)'
only_detached = true

[git_status]
format = '([($conflicted)($untracked)($modified)($deleted)($staged)($renamed)($stashed) $ahead_behind]($style) )'
style = 'purple'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = '\[⇡${ahead_count} ⇣${behind_count}\]'
conflicted = "[󰋔](red)"
untracked = "[?](red)"
modified = "[M](red)"
deleted = "[D](red)"
staged = "[+](green)"
renamed = "[R](green)"
stashed = '󱗞 '
#
# Prompt character
#

[character]
success_symbol = "[ △ ](bold green)"
error_symbol = "[ ▲ ](bold red)"

##
## Other stuff I'm less likely to use
##

[golang]
symbol = ""
disabled = true
format = "[ $symbol ($version) ]($style)"
version_format = "v${major}.${minor}"

[aws]
symbol = "󰸏 "

[package]
symbol = " "

[docker_context]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
