# Extra "Nerd Font characters"
#
# 󱠿       󰯈
# Ok, check this out - https://github.com/ryanoasis/powerline-extra-symbols
#

format = """
[╭─](green)$golang$nodejs[$fill───$memory_usage─⇾ $time $battery](green)
[│](green) $directory$git_branch$git_status
[╰ ](green)$character
"""

right_format = "$battery"
command_timeout = 5000

#
#   Top Line
#

[golang]
symbol = ""
format = "[ $symbol ($version) ]($style)"
version_format = "v${major}.${minor}"

[nodejs]
symbol = ""
format = " [ $symbol ](bg:green fg:black) [($version) ]($style)"

[fill]
symbol = "─"
style = "green"

[memory_usage]
symbol = " "
disabled = true
threshold = 25
format = "[](green)[ ${ram} :: ${ram_pct} ](bg:green fg:black bold)[](green) "

[time]
disabled = false
format="[$time](style)"
time_format = "%d %b %Y 󱠿 %T"

[battery]
format = "[$symbol]($style)"
full_symbol = "󰁹 "
empty_symbol = "󰂎 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁽 "
unknown_symbol = "󰂑 "

[[battery.display]]
threshold = 40
style = "yellow"

#
#   Middel Line
#

[directory]
truncation_length = 10

[git_branch]
symbol = " "
always_show_remote = true
format = '[$symbol$branch( 󰤉$remote_name)]($style) '

[git_status]
format = '([($conflicted)($untracked)($modified)($deleted)($staged)($renamed)($stashed) $ahead_behind]($style) )'
style = 'purple'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = '\[⇡${ahead_count} ⇣${behind_count}\]'
conflicted = "[=](red)"
untracked = "[?](red)"
modified = "[M](red)"
deleted = "[D](red)"
staged = "[+](green)"
renamed = "[R](green)"
stashed = '\$'

#
# Prompt character
#
[character]
success_symbol = "[△](bold green)"
error_symbol = "[▲](bold red)"




##
## Other stuff I'm less likely to use
##

[aws]
symbol = "󰸏 "

[package]
symbol = " "

[docker_context]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
