# Extra "Nerd Font characters"
#
# 󱠿   
# Ok, check this out - https://github.com/ryanoasis/powerline-extra-symbols
#

format = """
[╭─](green)$golang$nodejs[$fill───$memory_usage─⇾ $time $battery](green)
[│](green) $directory$git_branch$git_status
[╰ ](green)$character 
"""

right_format = "$battery"
command_timeout = 5000

# Prompt character
[character]
success_symbol = "[△](bold green)"
error_symbol = "[▲](bold red)"

[fill]
symbol = "─"
style = "green"

[battery]
format = "[$symbol]($style)"
full_symbol = "󰁹 "
empty_symbol = "󰂎 "
charging_symbol = "󰂄 "
discharging_symbol = "󰁽 "
unknown_symbol = "󰂑 "

[[battery.display]]
threshold = 40
style = "yellow"

[time]
disabled = false
format="[$time](style)"
time_format = "%d %b %Y 󱠿 %T"

[directory]
truncation_length = 10

[git_branch]
symbol = " "

[golang]
symbol = ""
format = "[ $symbol ($version) ]($style)"
version_format = "v${major}.${minor}"

[nodejs]
symbol = ""
format = " [ $symbol ](bg:green fg:black) [($version) ]($style)"

[memory_usage]
symbol = " "
disabled = true
threshold = 25
format = "[](green)[ ${ram} :: ${ram_pct} ](bg:green fg:black bold)[](green) "

##
## Other stuff I'm less likely to use
##

[aws]
symbol = "󰸏 "

[package]
symbol = " "

[docker_context]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

