#!/bin/bash

DOTS=$HOME/.dotfiles;
INSTALL=$DOTS/install;

source "$DOTS/utils/colors.sh";

echo "Pretend this is into with instructions ...";

## Install fish to run fish shell scripts for the rest
## of the setup and installation

# install Homebrew if missing
command -v brew > /dev/null || {
  echo -e "Homebrew is missing. ${bold:?}Installing homebrew.${stop:?}";
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)" # add `brew` to the PATH
}

# install fish
command -v fish &> /dev/null || {
  echo -e "Missing fish shell. ${bold:?}Installing fish shell.{$stop:?}";
  command -v brew &> /dev/null || {
    echo "${bold:?}Still missing homebrew.${stop:?}";
  }
  command -v brew &> /dev/null && {
    brew install fish;
  }
}

command -v fish &>/dev/null || {
  echo -e ${red:?}Fish not found${stop:?};
  exit 1;
}

command -v fish &> /dev/null && {
  fish $INSTALL/setup_profile;
}

command -v fish &> /dev/null && {
  fish $INSTALL/link_dotfiles;
}

command -v fish &> /dev/null && {
  fish $INSTALL/app_install;
}

command -v fish &> /dev/null && {
  fish $INSTALL/shell_setup;
}

command -v fish &> /dev/null && {
  fish $INSTALL/set_defaults;
}
# echo
# echo
# read -p "Do you want to install mac stuff? " -n 1 -r
# echo
# if [[ $REPLY =~ ^[Yy]$ ]]
# then
#   command -v fish > /dev/null && {
#     fish $DOTS/set_defaults
#   }
# fi
