# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# command line

install figlet
install tree
install wget

# casks
cask install google-chrome
cask install firefox
cask install hipchat
cask install intellij-idea-community
cask install iterm2
cask install kaleidoscope
cask install opera
cask install opera-next
cask install spotify
cask install virtualbox
cask install vlc

# Remove outdated versions from the cellar
cleanup
