
#
# This is OLD and BROKEN.
# Behold the new HOTNESS here (https://github.com/Homebrew/homebrew-brewdler)
#


# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# command line

install figlet
install irssi
install node
install shellcheck
install tree
install wget

# casks
cask install hipchat
cask install iterm2
cask install kaleidoscope
cask install spotify
cask install virtualbox
cask install vlc

# Remove outdated versions from the cellar
cleanup
